export const element = {
    id: (Date.now() + Math.random()).toString(),
    x: 0,
    y: 0,
    width: 100,
    height: 100,
    label: "Empty",
    label_left_position: 40,
    label_top_position: 40,
    bold: false,
    italic: false,
    bgColor: "#0081fa",
    textColor: "#000000",
    fontSize: 14,
    rotate: 0,
    fr_begin: 0,
    fr_end: 0,
    fr_text_rotate: 0,
    fr_text_top: -25,
    fr_text_left: -5,
    fr_text_size: 14,
    fr_text_color: "#000000",
    fr_text_position: "bottom",
    type: "Title",
    borderBox: 1,
    borderBoxColor: "#000000",
    visible_begin: true,
    visible_end: true,
    fr_distinction: false,
    measure: "kHz",
    visible_border_top:true,
    visible_border_right:true,
    visible_border_left:false,
    visible_border_bottom:true,
    border_top_value:1,
    border_right_value:1,
    border_bottom_value:1,
    border_left_value:1,
    borderColor:"#000000",
    order:  1,
    heightRow: 100,
}

